name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
env:
  VERSION: v1191111

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: printversion
      run: |
        echo "docker image version" $VERSION
    - name: testenv
      env:
        MY_VAR: Hello World!
        MY_NAME: P3TERX
      run: |
        make push IMAGES="tke-platform-api"
