name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
env:
  VERSION: v1191111

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
         fetch-depth: 2
    - name: checkout head
      run: git checkout HEAD^
    - name: printversion
      run: |
        echo "docker image version" $VERSION
    - name: docker-login
      uses: azure/docker-login@v1
      with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: testenv
      env:
        MY_VAR: Hello World!
        MY_NAME: P3TERX
      run: |
        make push IMAGES="tke-platform-api"
